### ISSUE TITLE
请教一下通过 docker-compose up -d 启动后，如何通过IP:PORT管理？

### ISSUE THREAD

**Issue by shangdev** [enwaiax/x-ui#19]
docker-compose.yml

```
version: "3.9"
services:
  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: xui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    ports:
      - "0.0.0.0:222:222"
    restart: unless-stopped
    network_mode: host
```

指定了端口为222，但是通过IP:222无法访问面板呢？

还是需要进入到容器内通过 x-ui 设置？
